name: sonarcloud-scan
on:
    push:
        branches: [main, fix-sonarcloud, default]
    

jobs:
    quality-gate:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v6
          - name: Set up Node.js
            uses: actions/setup-node@v6
            with:
                node-version: 24
          - name: Install Dependencies
            run: npm install
          - name: SonarCloud Scan
            uses: SonarSource/sonarqube-scan-action@v7.0.0
            env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: https://sonarcloud.io

    security-scan:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v6
          - name: Set up Node.js
            uses: actions/setup-node@v6
            with:
                node-version: 24
          - name: Install Dependencies
            run: npm ci
          - name: Build Docker image
            run: docker build -t todo-app:latest .
          - name: Run Trivy
            uses: aquasecurity/trivy-action@0.34.1
            with:
                image-ref: "todo-app:latest"
                format: "table"
                exit-code: 1
                ignore-unfixed: true
                severity: "CRITICAL"